version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: heroverse_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  # Go API Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heroverse_api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: